export interface Transaction {
  category: string;
  fromAccountId: string | null;
  fromAlias: null;
  fromOwner: string | null;
  fromSubaccount: null;
  id: string;
  op: string;
  source: string;
  sourceCanister: string;
  spenderAccountId: null;
  spenderAlias: null;
  spenderOwner: null;
  spenderSubaccount: null;
  toAccountId: string | null;
  toAlias: null;
  toOwner: string | null;
  toSubaccount: null;
  token0Amount: number;
  token0Decimal: number;
  token0Fee: number;
  token0LedgerId: string;
  token0Symbol: string;
  token0TxHash: null;
  token0TxIndex: number;
  token0TxMemo: null;
  token0TxTime: string;
  token0Value: number;
  token1Amount: number | null;
  token1Decimal: number | null;
  token1Fee: number | null;
  token1LedgerId: null;
  token1Symbol: null;
  token1TxHash: null;
  token1TxIndex: null;
  token1TxMemo: null;
  token1TxTime: null;
  token1Value: null;
}
